# Generated by Django 6.0 on 2025-12-26 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='seller_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.sellerproduct'),
        ),
    ]
