# Generated by Django 6.0 on 2025-12-26 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tracking_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordersellergroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.ordersellergroup')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.shippingprovider')),
            ],
        ),
    ]
